language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "wget https://raw.githubusercontent.com/biopython/biopython/master/Tests/GenBank/NC_005816.gb"
  - "make"
# command to run tests
script: 
  - "pep8 *.py*"
  - "cat NC_005816.gb | python main.py -f genbank"
