#include <string.h>
#include <libcalg-1.0/libcalg/trie.h>

typedef struct CodonCount {
    long long TTT;
    long long TTC;
    long long TTA;
    long long TTG;
    long long TCT;
    long long TCC;
    long long TCA;
    long long TCG;
    long long TAT;
    long long TAC;
    long long TAA;
    long long TAG;
    long long TGT;
    long long TGC;
    long long TGA;
    long long TGG;
    long long CTT;
    long long CTC;
    long long CTA;
    long long CTG;
    long long CCT;
    long long CCC;
    long long CCA;
    long long CCG;
    long long CAT;
    long long CAC;
    long long CAA;
    long long CAG;
    long long CGT;
    long long CGC;
    long long CGA;
    long long CGG;
    long long ATT;
    long long ATC;
    long long ATA;
    long long ATG;
    long long ACT;
    long long ACC;
    long long ACA;
    long long ACG;
    long long AAT;
    long long AAC;
    long long AAA;
    long long AAG;
    long long AGT;
    long long AGC;
    long long AGA;
    long long AGG;
    long long GTT;
    long long GTC;
    long long GTA;
    long long GTG;
    long long GCT;
    long long GCC;
    long long GCA;
    long long GCG;
    long long GAT;
    long long GAC;
    long long GAA;
    long long GAG;
    long long GGT;
    long long GGC;
    long long GGA;
    long long GGG;
}CodonCount;

CodonCount countcodons(char * sequence);